### ISSUE TITLE
Stop support for EOL Python versions

### ISSUE THREAD

**Issue by arcivanov** [fluent/fluent-logger-python#108]
2.7 is EOL in 2020 so it should be kept

3.2 is EOL Februrary 2016
3.3 is EOL September 2017

We should stop supporting these versions and clean-up code to remove hacks and workarounds.
Add python_requires constraint.

**Comment by arcivanov** [comment]
@repeatedly thoughts?

**Comment by repeatedly** [comment]
@arcivanov LGTM 👍
