### ISSUE TITLE
Updating version and git tags

### ISSUE THREAD

**Issue by EvaSDK** [fluent/fluent-logger-python#11]
Hi,

1/ could you please add tags to the repository ?
2/ could you please bump version number in setup.py, this would allow people (like me) who need the newer code to use dependency_links and adequate version requirements in setup.py to automatically fetch code from github rather than pypi.

TIA.

**Comment by kiyoto** [comment]
Sorry for the late response (and it looks like the original author @kzk came back to life 22 hours ago in which he merged some of your work).

Is this issue still active?

**Comment by kiyoto** [comment]
...and I will add tags shortly.

**Comment by kiyoto** [comment]
@EvaSDK tags are there, including the latest v0.3.5. Please check!

**Comment by EvaSDK** [comment]
This looks nice. Thanks.

**Comment by kiyoto** [comment]
No worries. sorry for relative inactivity in the past. Team Treasure Data has been busy.

It looks like you are using this library in earnest. would you be interested in maintaining it alongside?

**Comment by EvaSDK** [comment]
I am using it at work only and I am not sure how long this is job is going to continue for me, so I would sure be happy to help, just not sure it would be worth it for you guys.
