### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'emit_with_time'

### ISSUE THREAD

**Issue by jiuchongxiao** [fluent/fluent-logger-python#139]
asyncsender has erro
AttributeError: 'NoneType' object has no attribute 'emit_with_time'
detail:
python:3.6.5
pip:10.0.1 
![default](https://user-images.githubusercontent.com/13093730/40522926-c131a5fe-6005-11e8-805d-3e2bfbec9d60.png)

**Comment by arcivanov** [comment]
No, it doesn't. `fluent.event` uses `sender` and not the `asyncsender`. From the standpoint of `event` you haven't set up the global sender.

https://github.com/fluent/fluent-logger-python/blob/master/fluent/event.py#L11
https://github.com/fluent/fluent-logger-python/blob/master/fluent/sender.py#L26
https://github.com/fluent/fluent-logger-python/blob/master/fluent/asyncsender.py#L34

Those are different globals.

**Comment by jiuchongxiao** [comment]
@arcivanov i did as the document . and it apper the problem
![default](https://user-images.githubusercontent.com/13093730/40528939-3650ad20-6025-11e8-9d53-68dfab2b13d4.png)
