### ISSUE TITLE
Configuration with fileConfig

### ISSUE THREAD

**Issue by viskoo** [fluent/fluent-logger-python#145]
I have the problem with the python fileConfig parser, here is part of configuration that's causing problem
```
[handler_fluentdHandler]
class=fluent.handler.FluentHandler
level=DEBUG
host=localhost
port=12345
tag=logging.local
buffer_overflow_handler=null
formatter=fluentdFormater
args=(sys.stdout,)
```

I get the following error: 
`TypeError: can't serialize <open file '<stdout>', mode 'w' at 0x7f474dd74150>`
and i can't leave out args because they are mandatory

I have tried various options but can't seem to get it working

**Comment by viskoo** [comment]
I have found the solution, if anyone is interested here it is:
```
[handler_fluentdHandler]
class=fluent.handler.FluentHandler
level=DEBUG
formatter=fluentdFormater
args=("logging.local", "localhost", 12345)
```

**Comment by sss-cvs** [comment]
> I have found the solution, if anyone is interested here it is:
> 
> ```
> [handler_fluentdHandler]
> class=fluent.handler.FluentHandler
> level=DEBUG
> formatter=fluentdFormater
> args=("logging.local", "localhost", 12345)
> ```

Thanks.

Can you please share confiFile as sample to be used for fluent logger. I need definition of fluentdFormater
