### ISSUE TITLE
Is it possible to use fluent.asynchandler with Kubernetes DaemonSet

### ISSUE THREAD

**Issue by codeninja55** [fluent/fluent-logger-python#147]
Hi,

I currently have a deployment with a Kubernetes DaemonSet as per the official docs [here](https://github.com/fluent/fluentd-kubernetes-daemonset).

Is it possible to send logs from my Flask pod to this daemonset as I cannot find any documentation or examples anywhere. 

Any other suggestions if this is not possible?

**Comment by arcivanov** [comment]
Please try SOF. This is not an appropriate venue to ask for help with your projects or third party deployment solutions.
