### ISSUE TITLE
allow reading some configuration options from environment variables

### ISSUE THREAD

**Issue by jshen28** [fluent/fluent-logger-python#155]
Hi, do you think it is a good idea to allow some some options, such as `host`, `port`, to be configured from environment variables?

for example, here https://github.com/fluent/fluent-logger-python/blob/a37f31362fa89bfe9c3f701c91122fcc0dc8ebaa/fluent/handler.py#L185 , host has to be configured explicitly during object initialization.

By using enviroment variables, i think it will be more flexible for applications running in Kubernetes to get different addresses for each specific pod.

**Comment by arcivanov** [comment]
And what prevents you from initializing the handler from environmental variables right now by using `os.environ` or passing `os.environ` as a default to `argparse.add_argument` and using the `arg` in turn to initialize the handler?

I don't think it's a good idea at all. This is a library, not a utility and having environmentally-driven defaults with __hardcoded__ names can create a whole bunch of problems and unexpected and unintuitive behaviors.
