### ISSUE TITLE
Relax top end of Python version range specifier?

### ISSUE THREAD

**Issue by seansfkelley** [fluent/fluent-logger-python#161]
Would it be possible to relax the Python version specifier

https://github.com/fluent/fluent-logger-python/blob/e00bcdd8ee2bd36e470460770cb7ab8b91fa3f87/setup.py#L40

to not put a cap on the highest supported version? This is singlehandedly requiring all of the repos in my product to specify the same `<` rules as fluent-logger-python even though we control our Python version and generally support the latest release. 

Does fluent-logger-python do anything sufficiently weird that you would expect it to break on minor language versions? https://github.com/fluent/fluent-logger-python/issues/148 suggests "not really", and I would prefer to not block our language upgrades on fluent-logger-python when the duck types are likely to just work!

**Comment by arcivanov** [comment]
The version pin tries to indicate that there is no data on it being tested or even minimally functioning. But I suppose you're right, *caveat emptor* and all that. I'll relax the restriction.
