### ISSUE TITLE
logger.emit() method is not sending the data properly to fluentbit

### ISSUE THREAD

**Issue by 1999ankitgoyal** [fluent/fluent-logger-python#206]
Docker image used for fluentbit : [fluent/fluent-bit:latest](https://hub.docker.com/r/fluent/fluent-bit/).   This is fluentbit configuration :

```
[SERVICE]
    Flush           1
    Daemon          off
    Log_Level       info

[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5140
    Format      json
    Buffer_Size 10240
    Chunk_Size  1024
    Tag         app.*

[OUTPUT]
    Name        stdout
    Match       app.*
```

Required libraries are already installed. This is python3 code :
```
import os
import time
import logging
import requests
import socket
import json
import ipaddress 


from logging.handlers import SocketHandler
from pythonjsonlogger import jsonlogger
from fluent import sender, event


fluent_host = '127.0.0.1'
fluent_port = 5140

logger = sender.FluentSender('app', host='127.0.0.1', port=5140)
logger.emit('follow', {"from": "userA", "to": "userB"})
```

The error I am getting is :

![error](https://github.com/fluent/fluent-logger-python/assets/112812547/87f6b2e3-7aa1-41cb-b33d-62300d03f590)

But upon running the command from command line terminal,  the fluentbit is successfully able to read the message. 
`echo '{"from": "userA", "to": "userB"}' | ncat '127.0.0.1' 5140`

Is there some issue with my code or the emit method has some bug ? Could someone please help here.
Thank you

**Comment by methane** [comment]
Use forward, not tcp.
https://docs.fluentbit.io/manual/pipeline/inputs/forward
