### ISSUE TITLE
Master branch is not on latest version

### ISSUE THREAD

**Issue by rohan-97** [fluent/fluent-logger-python#209]
Hello,

I was building fluent-logger from master branch and found that the version is on 0.11.0 however latest version  [v0.11.1](https://github.com/fluent/fluent-logger-python/releases/tag/v0.11.1) was released on 6th June 2024

any idea when the version will be updated on master branch?

**Comment by methane** [comment]
Sorry. I did `git push origin master` instead of `git push upstream master`. So v0.11.1 was only at my fork.
Now I pushed the branch to this repo.
