### ISSUE TITLE
Python3 RecordFormatter is broken (and undocumented)

### ISSUE THREAD

**Issue by quasipedia** [fluent/fluent-logger-python#23]
In order for the plugin to output data that can be correctly parsed by `fluentd` when it will forward it to some storage like for example `elasticsearch`, it is necessary to use the [RecordFormatter](https://github.com/fluent/fluent-logger-python/blob/master/fluent/handler.py#L14) class on the logging handler.

However, there are two issues:

  1. The need for this step is undocumented
  2. The code in the plugin is python2-compatible only, as it uses the [`basestring`](https://github.com/fluent/fluent-logger-python/blob/master/fluent/handler.py#L47)

**Comment by EvaSDK** [comment]
This should be solved in v0.4.0.
