### ISSUE TITLE
handling connection error between fluentd

### ISSUE THREAD

**Issue by yudai09** [fluent/fluent-logger-python#25]
I want to use this module within a cron script for my project.
However, I can't find the way handling connection error between my script and fluentd.

As long as I understand, this modules runs as follow way, so cron scripts (not daemon programs) cannot handle the connection problems.

1. when it can't connect to fluentd, data will be stored in a buffer. 
2. And it does not return any error, nor call error handler function.

At least, I should know my script have remaining log in the buffer.
Please tell me how to handle connection errors between my script and fluentd.

**Comment by aehlke** [comment]
Please see this fork: https://github.com/yudai09/fluent-logger-python/commit/8b6c3c8481896ccab7e1eb19d3501251d6ac9f93

**Comment by yudai09** [comment]
this is my fork:)
can you accept my pull request?

**Comment by starkers** [comment]
Please accept his pull request already!

**Comment by aehlke** [comment]
We have been happily using yudai09's fork, FWIW :)

**Comment by starkers** [comment]
Ye I'll evaluate it today, our code was changed to just use in_http and requests (cause at least in_http bothers to speak back lol)

**Comment by hir3npatel** [comment]
@aehlke how exactly are you using the fork, do you check for an error after each event creation using the last_error() method of sender?
@starkers where did you change it to use in_http? I am facing a similar issue described in this thread and looking around for a solutions. Thanks.

**Comment by aehlke** [comment]
@hir3npatel it's just a property - we check it after every event creation

**Comment by repeatedly** [comment]
Sorry for missing this issue. I forgot to set slack notificaiton...

@yudai09 's patch is good for me. fluent-logger-ruby also has same feature.
PRs are welcome :)

**Comment by repeatedly** [comment]
I merged https://github.com/fluent/fluent-logger-python/pull/59 and this issue should be resolved.
