### ISSUE TITLE
override time

### ISSUE THREAD

**Issue by pi3ch** [fluent/fluent-logger-python#35]
I am reading records from a file and time should be set as the recorded time in the file not the time I send the record to fluent receiver (i.e. in_forwarder)

I am trying to override the time by including a time key in the event message. I tried combination of both `time` and `timestamp` with different formatting. It seems like the receiver disregard this key and honour time set by the handler. 

Is there anyway to override the event time?

https://github.com/fluent/fluent-logger-python/blob/master/fluent/sender.py#L53

**Comment by repeatedly** [comment]
`emit_with_time` is not fit for your case?

**Comment by repeatedly** [comment]
No response. If you have a problem with `emit_with_time`, please reopen it.
