### ISSUE TITLE
retry support

### ISSUE THREAD

**Issue by icy** [fluent/fluent-logger-python#46]
Current version of the module doesn't retry if error occurs during the last connection (connection lost, timeout, ...); So a message is sent, or discarded without notice.

This is quite different from the behavior of Java, Ruby client. 

Please fix that. Thank you very much.

**Comment by repeatedly** [comment]
Sorry for the delay.
https://github.com/fluent/fluent-logger-python/issues/25 's patch may resolve this issue.

**Comment by icy** [comment]
Thanks a lot, @repeatedly !
