### ISSUE TITLE
FluentRecordFormatter not compatible with Python 3.2+ Formatter

### ISSUE THREAD

**Issue by jt1** [fluent/fluent-logger-python#63]
From Python 3.2 `logging.Formatter` `__init__` method has extra parameter `style`:
```python 
def __init__(self, fmt=None, datefmt=None, style='%'):
```
but `fluent.handler.FluentRecordFormatter` does not have it:
```python
def __init__(self, fmt=None, datefmt=None):
```
Problem appears when reading logging configuration from a ConfigParser-format file using
`logging.fileConfig` (e.g. loading logging configuration from Pyramid ini file). 
When `logging.config._create_formatters` runs `f = c(fs, dfs, stl)` following exception is raised:
`TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given`

I suggest to add `style` parameter to `fluent.handler.FluentRecordFormatter` `__init__` definition.

**Comment by repeatedly** [comment]
Thanks for the report.
I just wrote a patch by using your suggestion.
Could you check the patch? > https://github.com/fluent/fluent-logger-python/pull/65

**Comment by jt1** [comment]
Thanks for the patch.
Your fix is identical with

**Comment by jt1** [comment]
Thanks for the patch.
It work fine for me in Python 2.7 and 3.2+

**Comment by repeatedly** [comment]
Thanks for the test.
I will release new version soon.

**Comment by repeatedly** [comment]
Release v0.4.4.
