### ISSUE TITLE
StreamHandler format customisation

### ISSUE THREAD

**Issue by nicolaevladescu** [fluent/fluent-logger-python#68]
Hello.

I noticed that the logs are also outputted to stdout via a StreamHandler with default format.

How do i disable this so that i can attach my own StreamHandler and customise it, or how can i change the format of the one that the module attaches? I would like to send a different format to fluentd and another to console.

From what i can see on the README, the example using `logging.config.dictConfig` seems to be able to change that, however i am looking for a simpler way.

Thank you.

**Comment by repeatedly** [comment]
Can someone reply this question?
I'm not familiar with python logging module, so I can't answer...

**Comment by methane** [comment]
logging.basicConfig make default StreamHandler with default format.
So just stop using logging.basicConfig.

**Comment by nicolaevladescu** [comment]
Hello.

Thank you, that solved it!

I will leave my code here maybe it can help somebody else, this is how i use it:

```python
import sys
import logging
from fluent import handler


LOG = logging.getLogger('app-stdout')
ERR = logging.getLogger('app-stderr')

LOG.setLevel(logging.DEBUG)
ERR.setLevel(logging.ERROR)

STDOUT_HANDLER = logging.StreamHandler(stream=sys.stdout)
STDERR_HANDLER = logging.StreamHandler(stream=sys.stderr)

STDOUT_HANDLER.setLevel(logging.DEBUG)
STDERR_HANDLER.setLevel(logging.ERROR)

STD_FORMAT = logging.Formatter(
    '%(asctime)s - %(levelname)s - %(message)s'
)

STDOUT_HANDLER.setFormatter(STD_FORMAT)
STDERR_HANDLER.setFormatter(STD_FORMAT)

FLUENT_HANDLER = handler.FluentHandler(
    FLUENT_TAG, host=FLUENT_HOST, port=int(FLUENT_PORT)
)

FLUENT_HANDLER.setFormatter(handler.FluentRecordFormatter({
    'when': '%(asctime)s',
    'host': '%(hostname)s',
    'where': '%(module)s.%(funcName)s',
    'type': '%(levelname)s',
    'stack_trace': '%(exc_text)s'
}))

LOG.addHandler(STDOUT_HANDLER)
LOG.addHandler(FLUENT_HANDLER)

ERR.addHandler(STDERR_HANDLER)
ERR.addHandler(FLUENT_HANDLER)

# Example usage
LOG.debug('Program started')
ERR.critical('Cannot start, port %s already in use', APP_PORT)
```
