### ISSUE TITLE
Fluent logger fails to serialize exceptions.

### ISSUE THREAD

**Issue by redlolgeerf** [fluent/fluent-logger-python#69]
Here is a simple script to illustrate the problem:

```#!/usr/bin/env python

import os
import logging
from fluent import handler


FLUENT_HOST = os.getenv('FLUENT_HOST', 'fluentd-logger')
FLUENT_PORT = int(os.getenv('FLUENT_PORT', 24224))
FLUENT_TAG = os.getenv('FLUENT_TAG', 'docker.docker-tag')

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('fluent.test')
    h = handler.FluentHandler(FLUENT_TAG, host=FLUENT_HOST, port=FLUENT_PORT, verbose=True)
    formatter = handler.FluentRecordFormatter()
    h.setFormatter(formatter)
    logger.addHandler(h)

    logger.info(Exception('foo'))
```

this produces:
('docker.docker-tag', 1481107415, {'sys_module': 'script', 'message': Exception('foo',), 'sys_name': 'fluent.test', 'sys_host': 'K501LB'})
('docker.docker-tag', 1481107415, {'message': "Can't output to log", 'traceback': 'Traceback (most recent call last):\n  File "/tmp/fl/.venv/local/lib/python2.7/site-packages/fluent/sender.py", line 69, in emit_with_time\n    bytes_ = self._make_packet(label, timestamp, data)\n  File "/tmp/fl/.venv/local/lib/python2.7/site-packages/fluent/sender.py", line 101, in _make_packet\n    return msgpack.packb(packet)\n  File "/tmp/fl/.venv/local/lib/python2.7/site-packages/msgpack/__init__.py", line 47, in packb\n    return Packer(**kwargs).pack(o)\n  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)\n  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)\n  File "msgpack/_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)\n  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)\n  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)\nTypeError: can\'t serialize Exception(\'foo\',)\n', 'level': 'CRITICAL'})
INFO:fluent.test:foo

**Comment by mikeshi80** [comment]
I got the same problem. And protobuf object cannot be serialized either, but the built-in stream handler can do it.

**Comment by taormania** [comment]
I have the same issue. This is prevent my logs from being sent in the correct format. Is there any projected fix for this?

**Comment by repeatedly** [comment]
This is because msgpack doesn't know how to serialize Exception class.
So you need to tell how to serialize unknown class.
Current version supports `msgpack_kwargs` attribute for it.
Here is an example:

```
import os
import logging
from fluent import handler

FLUENT_HOST = os.getenv('FLUENT_HOST', '127.0.0.1')
FLUENT_PORT = int(os.getenv('FLUENT_PORT', 24224))
FLUENT_TAG = os.getenv('FLUENT_TAG', 'test.log')

def encode_exception(obj):
    if isinstance(obj, Exception):
        return {"class":"exception", "args":obj.args}
    return obj

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('fluent.test')
    h = handler.FluentHandler(FLUENT_TAG, host=FLUENT_HOST, port=FLUENT_PORT, verbose=True)
    h.sender.msgpack_kwargs = {
        'default' : encode_exception
    }
    formatter = handler.FluentRecordFormatter()
    h.setFormatter(formatter)
    logger.addHandler(h)

    logger.info(Exception('foo'))
```

**Comment by repeatedly** [comment]
Release v0.5.3 with msgpack_kwargs support in `FluentHandler`.
No need to access internal attribute.

```
import os
import logging
from fluent import handler

FLUENT_HOST = os.getenv('FLUENT_HOST', '127.0.0.1')
FLUENT_PORT = int(os.getenv('FLUENT_PORT', 24224))
FLUENT_TAG = os.getenv('FLUENT_TAG', 'test.log')

def encode_exception(obj):
    if isinstance(obj, Exception):
        return {"class":type(obj).__name__, "args":obj.args}
    return obj

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('fluent.test')
    h = handler.FluentHandler(FLUENT_TAG, host=FLUENT_HOST, port=FLUENT_PORT, msgpack_kwargs={'default' : encode_exception}, verbose=True)
    formatter = handler.FluentRecordFormatter()
    h.setFormatter(formatter)
    logger.addHandler(h)

    logger.info(Exception('foo'))
```

**Comment by hemanthactionfi** [comment]
i was using Django, So i did this
`        'fluentd': {
            'level': 'INFO',
            'class': 'fluent.handler.FluentHandler',
            'formatter': 'fluentd',
            'tag': 'default.logs',
            'host': 'localhost',
            'port': 24224,
            'timeout':3.0,
            'verbose': True,
            "msgpack_kwargs":{'default' : str}
        }, `
