### ISSUE TITLE
Why kwargs in FluentSender?

### ISSUE THREAD

**Issue by luhn** [fluent/fluent-logger-python#83]
I noticed that `FluentSender` has `**kwargs`, but it's a blackhole—The values are never used.

Is there a reason for that to be there?  If not, it should be removed.

This would be a backwards-incompatible change, so it would need to wait until the next major release.

**Comment by repeatedly** [comment]
> Is there a reason for that to be there? If not, it should be removed.

It seems historical reason. I just added comment for it.
Thanks for pointing this out.
