### ISSUE TITLE
how to add buffer_overflow_handler rightly to make the pendings send ok?

### ISSUE THREAD

**Issue by jiamo** [fluent/fluent-logger-python#86]
As the title said. The  ` sender.pendings` already `> self.bufmax`. If I what to send this pending, how to do?
In  `_send_internal` function

        if self.pendings:
            self.pendings += bytes_
            bytes_ = self.pendings
   
I think we should not directly add these bytes . If it will overflow. How about send the pending first then send the bytes?

**Comment by arcivanov** [comment]
The buffer can be temporarily overflowed for sure but both `pendings` and `bytes` are concatenated, there is an attempt to send and if it fails both go into overflow.
