### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'emit_with_time'

### ISSUE THREAD

**Issue by wanghaisheng** [fluent/fluent-logger-python#93]
```
(py3.6) ➜  ocrla git:(master) ✗ pip install fluent-logger==0.5.2
Collecting fluent-logger==0.5.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/76/f6/58fa7355a484b9d9c236d6c6b97e1bb148f1b076e5d252c2bc8570fde079/fluent_logger-0.5.2-py2.py3-none-any.whl
Requirement already satisfied: msgpack-python in /Users/wanghaisheng/anaconda/envs/py3.6/lib/python3.6/site-packages (from fluent-logger==0.5.2)
Installing collected packages: fluent-logger
  Found existing installation: fluent-logger 0.5.3
    Uninstalling fluent-logger-0.5.3:
      Successfully uninstalled fluent-logger-0.5.3
Successfully installed fluent-logger-0.5.2
(py3.6) ➜  ocrla git:(master) ✗ python local_image.py -i../../IMG_20170922_142015.jpg 
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/wanghaisheng/anaconda/envs/py3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/ocrap/ocrla/process.py", line 61, in run
    log_utils.log_info('Starting thread: %s' % self.method, self.guid)
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/ocrap/ocrla/utils/log_utils.py", line 41, in log_info
    event.Event('INFO', {'message': message, 'environment': config.environment, 'guid': guid})
  File "/Users/wanghaisheng/anaconda/envs/py3.6/lib/python3.6/site-packages/fluent/event.py", line 13, in __init__
    sender_.emit_with_time(label, timestamp, data)
AttributeError: 'NoneType' object has no attribute 'emit_with_time'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/wanghaisheng/anaconda/envs/py3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/ocrap/ocrla/process.py", line 61, in run
    log_utils.log_info('Starting thread: %s' % self.method, self.guid)
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/ocrap/ocrla/utils/log_utils.py", line 41, in log_info
    event.Event('INFO', {'message': message, 'environment': config.environment, 'guid': guid})
  File "/Users/wanghaisheng/anaconda/envs/py3.6/lib/python3.6/site-packages/fluent/event.py", line 13, in __init__
    sender_.emit_with_time(label, timestamp, data)
AttributeError: 'NoneType' object has no attribute 'emit_with_time'

Traceback (most recent call last):
  File "local_image.py", line 55, in <module>
    begin_processing_image(image_path, image_key, output_path, guid, None, is_local=True)
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/ocrap/ocrla/process.py", line 435, in begin_processing_image
    log_utils.log_info('Processing complete. processing_time:%s' % (time_end - time_start), guid)
  File "/Users/wanghaisheng/workspace/OCR/binarization-experiments/ocrap/ocrla/utils/log_utils.py", line 41, in log_info
    event.Event('INFO', {'message': message, 'environment': config.environment, 'guid': guid})
  File "/Users/wanghaisheng/anaconda/envs/py3.6/lib/python3.6/site-packages/fluent/event.py", line 13, in __init__
    sender_.emit_with_time(label, timestamp, data)
AttributeError: 'NoneType' object has no attribute 'emit_with_time'
(py3.6) ➜  ocrla git:(master) ✗ 

```

**Comment by repeatedly** [comment]
Please paste your code togeter.
We are not a Psychics :)

**Comment by wanghaisheng** [comment]
@repeatedly  https://github.com/zhanmer/ocrap

**Comment by repeatedly** [comment]
Could you check the fluent-logger usage is wrong or not in above project?
I want to know the minimal case of your problem.

**Comment by arcivanov** [comment]
Please reopen if this comes back.

**Comment by jiuchongxiao** [comment]
i have the same erro,did you solved? @wanghaisheng

**Comment by alexander-mayr** [comment]
+1 can confirm.

`
from fluent import asyncsender as sender
from fluent import event

sender.setup('app', host='fluentd', port=24224)
event.Event('got something', { "some": "thing"})
`

same code works with the sender module

**Comment by arcivanov** [comment]
@alexander-mayr what version are you using?

**Comment by arcivanov** [comment]
Well, actually it doesn't matter. `fluent.sender` and `fluent.asyncsender` are fundamentally different modules. Yes, injecting a sender into the event is the predesigned way to do it. That said, I would highly recommend not using global senders - they can't really be flushed reliably and produce very awkward code.

**Comment by alexander-mayr** [comment]
@arcivanov so.... if it doesn't matter which version I use then this is intended behaviour? you should update the documentation then because the way described there seems not to work and show the correct way of doing this.

**Comment by arcivanov** [comment]
@alexander-mayr this is the behavior as written. There is no absolute global sender, it's per module (`sender` vs `asyncsender`). The event.Event will use sender from `sender` unless a different sender specified as a parameter.

I would highly recommend to NOT use this API at all, it's ill-conceived and will not shutdown properly when Python quits so you're bound to lose messages. You also can't detect failures.

**Comment by chaseYLC** [comment]
> @alexander-mayr this is the behavior as written. There is no absolute global sender, it's per module (`sender` vs `asyncsender`). The event.Event will use sender from `sender` unless a different sender specified as a parameter.
> 
> I would highly recommend to NOT use this API at all, it's ill-conceived and will not shutdown properly when Python quits so you're bound to lose messages. You also can't detect failures.


The reason I want to use 'asyncsender' is because of the blocking problem when using 'sender'. Of course, I am sorry that 'asyncsender' does not detect failure. We hope to provide a callback function for errors.

I wonder how you handle the blocking problem that arises when you use a synchronous function. Could you let me know?
